// ArkM Electron 前端 — 稳健版（state + spectrum 封装）
const API = `http://localhost:${new URLSearchParams(location.search).get('port') || '8585'}`;
const audio = document.getElementById('audio-player');
const spectrum = new SpectrumEngine('spectrum', audio);

function log(msg){const el=document.getElementById('log-output');if(!el)return;el.textContent+=`[${new Date().toLocaleTimeString()}] ${msg}\n`;el.scrollTop=el.scrollHeight}

// 视图切换
function switchView(idx){state.currentView=idx;document.getElementById('search-input').value='';document.getElementById('cover-grid').innerHTML='';spectrum.stop();loadCoverGrid(state.nextViewId())}

// 聚合 API 加载
async function loadCoverGrid(myViewId){const grid=document.getElementById('cover-grid');
  if(state.currentView===2){for(const name of state.playHistory){if(state.isStale(myViewId))return;const c=document.createElement('div');c.className='cover-card';c.title=name;let img='<div class="card-placeholder"></div>';try{const r=await fetch(`${API}/music/${encodeURIComponent(name)}/album`).catch(()=>null);if(!r||state.isStale(myViewId))return;const a=(r.status===404)?null:await r.json().catch(()=>null);if(a&&a.album_cid)img=`<img src="${API}/album/${a.album_cid}/cover" onerror="this.parentElement.innerHTML='<div class=card-placeholder></div>'">`}catch{}c.innerHTML=img+`<div class="card-name">${name}</div>`;c.addEventListener('dblclick',()=>playMusic(name));c.addEventListener('contextmenu',e=>{e.preventDefault();showContextMenu(e.clientX,e.clientY,name)});grid.appendChild(c)}log(`最近播放: ${state.playHistory.length} 首`);return}
  const kind=state.currentView===0?'undownloaded':'downloaded';const r=await fetch(`${API}/view/${kind}`).catch(()=>null);if(!r||state.isStale(myViewId))return;const d=await r.json().catch(()=>({}));const songs=d.songs||[];if(state.isStale(myViewId))return;for(const s of songs){if(state.isStale(myViewId))return;const c=document.createElement('div');c.className='cover-card';c.title=s.name;c.innerHTML=(s.cover_url?`<img src="${API}${s.cover_url}" onerror="this.parentElement.innerHTML='<div class=card-placeholder></div>'">`:'<div class="card-placeholder"></div>')+`<div class="card-name">${s.name}</div>`;c.addEventListener('dblclick',()=>{state.currentView===0?downloadMusic(s.name):playMusic(s.name)});c.addEventListener('contextmenu',e=>{e.preventDefault();showContextMenu(e.clientX,e.clientY,s.name)});grid.appendChild(c)}log(`${state.currentView===0?'待下载':'已下载'}: ${songs.length} 首`)}

// 下载/删除
function updateDlStatus(){const s=document.getElementById('download-status');const n=state.downloadQueue.length;s.style.display=(state.downloading||n)?'flex':'none';s.textContent=state.downloading?`⬇ 下载中... 队列: ${n} 首`:`队列: ${n} 首`}
async function _doDownload(name){state.downloading=true;updateDlStatus();try{const r=await fetch(`${API}/music/download`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({music_name:name})});const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(true){const{done,value}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});const lines=buf.split('\n');buf=lines.pop();for(const l of lines)if(l.startsWith('data: ')){const d=JSON.parse(l.slice(6));if(d.type==='result'){log(d.message);switchView(state.currentView)}}}}catch(e){log(`下载失败: ${e.message}`)}state.downloading=false;if(state.downloadQueue.length){_doDownload(state.downloadQueue.shift())}else{updateDlStatus()}}
async function downloadMusic(name){if(state.downloading){state.downloadQueue.push(name);log(`已加入下载队列: ${name}`);updateDlStatus();return}if(!confirm(`确定下载《${name}》吗？`))return;log(`开始下载: ${name}`);_doDownload(name)}
async function deleteMusic(name){if(!confirm(`确定删除《${name}》？此操作不可撤销！`))return;try{const r=await fetch(`${API}/music/delete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({music_name:name})});const d=await r.json();log(d.message);switchView(state.currentView)}catch(e){log(`删除失败: ${e.message}`)}}

// 播放
function playMusic(name){state.playQueue=state.playQueue.filter(n=>n!==name);state.playQueue.unshift(name);playNext()}
function playNext(){if(!state.playQueue.length){state.currentMusic=null;return}state.currentMusic=state.playQueue.shift();audio.src=`${API}/stream/${encodeURIComponent(state.currentMusic)}`;audio.load();audio.play().catch(e=>log(`播放失败: ${e.message}`));document.getElementById('popup-song-title').textContent=state.currentMusic;document.getElementById('bar-song-name').textContent=state.currentMusic;updatePopupCover(state.currentMusic);updateQueueUI();log(`正在播放: ${state.currentMusic}`);state.playHistory=state.playHistory.filter(n=>n!==state.currentMusic);state.playHistory.unshift(state.currentMusic);if(state.playHistory.length>50)state.playHistory.pop()}
function togglePlayPause(){if(!state.currentMusic){log('请先选择歌曲');return}audio.paused?audio.play():audio.pause()}
function updatePopupCover(name){fetch(`${API}/music/${encodeURIComponent(name)}/album`).then(r=>r.json()).then(a=>{if(a&&a.album_cid){document.getElementById('popup-cover').src=`${API}/album/${a.album_cid}/cover`;document.getElementById('bar-cover-btn').style.backgroundImage=`url(${API}/album/${a.album_cid}/cover)`}}).catch(()=>{})}
function updateQueueUI(){document.getElementById('popup-queue-list').innerHTML=state.playQueue.map(n=>`<li class="${n===state.currentMusic?'current':''}" onclick="window._clickQueueItem('${n}')">${n}</li>`).join('')}
window._clickQueueItem=name=>{state.playQueue=state.playQueue.filter(n=>n!==name);state.playQueue.unshift(name);playNext()}

// 弹出面板
function togglePopup(mode){const p=document.getElementById('popup-panel');if(state.popupMode===mode&&p.classList.contains('open')){p.classList.remove('open');return}state.popupMode=mode;if(mode==='cover'){document.getElementById('popup-cover-area').style.display='';document.getElementById('popup-queue-list').style.display='none';if(state.currentMusic)updatePopupCover(state.currentMusic)}else{document.getElementById('popup-cover-area').style.display='none';document.getElementById('popup-queue-list').style.display='';updateQueueUI()}p.classList.add('open')}

// 右键菜单
function showContextMenu(x,y,name){const old=document.getElementById('ctx-menu');if(old)old.remove();const m=document.createElement('div');m.id='ctx-menu';Object.assign(m.style,{position:'fixed',left:x+'px',top:y+'px',background:'rgba(35,35,35,0.95)',border:'1px solid #555',borderRadius:'6px',padding:'4px 0',minWidth:'140px',zIndex:'9999',backdropFilter:'blur(6px)',animation:'fadeIn 0.15s ease'});m.addEventListener('click',e=>e.stopPropagation());const items=state.currentView===0?[{label:'⬇ 下载',action:()=>downloadMusic(name)}]:[{label:'▶ 播放',action:()=>playMusic(name)},{label:'📋 加入队列',action:()=>{state.playQueue.push(name);updateQueueUI();log(`已加入队列: ${name}`)}},{type:'sep'},{label:'🗑 删除',action:()=>deleteMusic(name)}];for(const it of items){if(it.type==='sep'){const s=document.createElement('div');s.style.cssText='height:1px;background:#444;margin:4px 8px';m.appendChild(s)}else{const el=document.createElement('div');el.textContent=it.label;el.style.cssText='padding:8px 14px;font-size:13px;color:#ccc;cursor:pointer';el.addEventListener('mouseenter',()=>{el.style.background='rgba(80,80,80,0.5)';el.style.color='#fff'});el.addEventListener('mouseleave',()=>{el.style.background='';el.style.color='#ccc'});el.addEventListener('click',e=>{e.stopPropagation();it.action();m.remove()});m.appendChild(el)}}document.body.appendChild(m)}

// 初始化
document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('.nav-btn').forEach(btn=>{btn.addEventListener('mousedown',e=>{e.preventDefault();document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');switchView(parseInt(btn.dataset.view))})});
  let _st=null;document.getElementById('search-input').addEventListener('input',e=>{clearTimeout(_st);_st=setTimeout(()=>{const kw=e.target.value.toLowerCase();document.querySelectorAll('.cover-card').forEach(c=>{c.style.display=(kw&&!c.querySelector('.card-name')?.textContent.toLowerCase().includes(kw))?'none':''})},100)});
  document.getElementById('btn-play').addEventListener('click',togglePlayPause);
  document.getElementById('btn-pause').addEventListener('click',()=>{audio.pause();audio.currentTime=0;log('已停止');state.currentMusic=null;document.getElementById('popup-song-title').textContent='';document.getElementById('bar-song-name').textContent='未在播放';document.getElementById('progress-bar').value=0;document.getElementById('time-label').textContent='00:00 / 00:00'});
  document.getElementById('progress-bar').addEventListener('input',()=>{if(audio.duration)audio.currentTime=(document.getElementById('progress-bar').value/1000)*audio.duration});
  document.getElementById('volume-bar').addEventListener('input',e=>{audio.volume=e.target.value/100});audio.volume=.5;document.getElementById('volume-bar').value=50;
  audio.addEventListener('ended',()=>{setTimeout(playNext,200)});
  audio.addEventListener('timeupdate',()=>{if(audio.duration){const p=(audio.currentTime/audio.duration)*100;document.getElementById('progress-bar').value=(audio.currentTime/audio.duration)*1000;document.getElementById('progress-bar').style.setProperty('--progress',p+'%');document.getElementById('time-label').textContent=`${new Date(audio.currentTime*1000).toISOString().slice(14,19)} / ${new Date(audio.duration*1000).toISOString().slice(14,19)}`}});
  const pi=document.querySelector('#btn-play i');audio.addEventListener('play',()=>{document.getElementById('btn-play').classList.add('playing');if(pi)pi.textContent='pause';spectrum.start()});audio.addEventListener('pause',()=>{document.getElementById('btn-play').classList.remove('playing');if(pi)pi.textContent='play_arrow';spectrum.stop()});
  document.getElementById('bar-cover-btn').addEventListener('click',()=>togglePopup('cover'));document.getElementById('bar-queue-btn').addEventListener('click',()=>togglePopup('queue'));
  document.getElementById('log-toggle').addEventListener('click',()=>{const p=document.getElementById('log-panel');p.classList.toggle('collapsed');const i=document.querySelector('#log-toggle i');if(i)i.textContent=p.classList.contains('collapsed')?'chevron_left':'chevron_right'});
  document.getElementById('log-clear').addEventListener('click',()=>{document.getElementById('log-output').textContent=''});
  document.getElementById('min-btn').addEventListener('click',()=>{if(window.arkm?.minimize)window.arkm.minimize();});document.getElementById('close-btn').addEventListener('click',()=>{if(window.arkm?.hide)window.arkm.hide();});
  document.addEventListener('click',e=>{if(!e.target.closest('#ctx-menu')){const m=document.getElementById('ctx-menu');if(m)m.remove()}},true);
  switchView(0);log('ArkM 初始化完成');
});
